services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - N8N_PROTOCOL=http
      - N8N_HOST=localhost
      - WEBHOOK_URL=http://localhost:5678
      - N8N_PORT=5678
      - N8N_ENCRYPTION_KEY=XrqhOVW5oJBTHwGjXGuZ8lduFsL6TyaJ
      - GENERIC_TIMEZONE=Asia/Colombo
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=168
      - N8N_BLOCK_ENV_ACCESS_IN_EXPRESSIONS=false
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - SERPER_API_KEY=${SERPER_API_KEY}
      - HUNTER_API_KEY=${HUNTER_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n_local:/n8n_local  # For local file storage

volumes:
  n8n_data: