services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_PROTOCOL=http
      - N8N_HOST=localhost
      - WEBHOOK_URL=http://localhost:5678
      - N8N_PORT=5678
      - N8N_ENCRYPTION_KEY=XrqhOVW5oJBTHwGjXGuZ8lduFsL6TyaJ
      - GENERIC_TIMEZONE=Asia/Colombo
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=168
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n_local:/n8n_local  # For local file storage

volumes:
  n8n_data: